### ISSUE TITLE
make go-rpm error: import cycle not allowed

### ISSUE THREAD

**Issue by tjyang** [cavaliercoder/go-rpm#1]
Hi there

Can you advise where I may have done wrong ?

'''
1. git clone https://github.com/cavaliercoder/go-rpm.git
2. cd go-rpm
3. go environment
[pi@centos7t02 go-rpm]$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pi/gocode"
GORACE=""
GOROOT="/home/pi/ws/go"
GOTOOLDIR="/home/pi/ws/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
4. build error message
[pi@centos7t02 go-rpm]$ make
go build -x
WORK=/tmp/go-build620429315
import cycle not allowed
package .
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
make: *** [build] Error 1
[pi@centos7t02 go-rpm]$ 

'''

**Comment by cavaliercoder** [comment]
Odd... which version of Go are you using?

Have you tried using `go get` instead of `git clone/make`?

**Comment by cavaliercoder** [comment]
It looks like your `$GOROOT` and `$GOPATH` are pointing to a library version that differs from your go binary version.

Please see:

* http://stackoverflow.com/questions/35168558/go-1-5-to-1-6-import-cycle-not-allowed
* https://github.com/golang/go/issues/13501

**Comment by tjyang** [comment]
Thanks for the pointers.
