### ISSUE TITLE
Which methods to parse primary.xml.gz, filelists.xml.gz, other.xml.gz files?

### ISSUE THREAD

**Issue by mcandre** [cavaliercoder/go-rpm#21]
Could there be API methods for parsing/validating the primary.xml.gz, filelists.xml.gz, and/or other.xml.gz files?

https://blog.packagecloud.io/eng/2015/07/20/yum-repository-internals/

**Comment by cavaliercoder** [comment]
I did start work on this, but it proved a little too difficult and not that useful, given the extensive Python API already available. I'd be happy to revisit if you have a strong use case.

Here's the how far I made it (in a branch on Y10K project): https://github.com/cavaliercoder/y10k/tree/native_rpm/yum

**Comment by cavaliercoder** [comment]
I think the biggest problem was there was no good Go implementation of the XZ compression format used by yum.
