### ISSUE TITLE
Extra requires is defined

### ISSUE THREAD

**Issue by bayrinat** [cavaliercoder/go-rpm#6]
For my test rpm I have extra requires: 
```
rpmlib(CompressedFileNames)
rpmlib(FileDigests)
rpmlib(PayloadFilesHavePrefix)
rpmlib(PayloadIsXz)

```
rpm was made on Ubuntu.

**Comment by cavaliercoder** [comment]
Is this a question? I don't understand sorry. If you're having trouble with a particular package, please post a link to it.

**Comment by bayrinat** [comment]
Sorry for bad description.
My rpm has only N requires. But when I parse it with rpm.ReadPackageFile() I have in requires slice all my requires plus four requires (from the first message).
I suppose it isn't correct behaviour. Why do I have this additional requires?
