### ISSUE TITLE
generate metadata for yum

### ISSUE THREAD

**Issue by vtolstov** [cavaliercoder/go-rpm#9]
I need something special:
i have ci system that exports builded rpm to external amazon s3 like host in dirs like /pkg-one /pkg-two ...
i need to generate metadata for using with yum/dnf tool in pkg-one pkg-two ...
i need to generate metadata in /release/ combined with pkg-one pkg-two...

something like mergerepo_c or updaterepo_c ...

how can i do this using this package?

**Comment by cavaliercoder** [comment]
This package does not currently support package repositories - only the RPM file format itself.
I have started work trying to implement `createrepo` in another project. See https://github.com/cavaliercoder/y10k/tree/native_rpm/yum

This implementation has a few issues. Implementing a yum repo requires creating XML documents, SQLite databases, XZ archives, etc., etc.. It might not really be feasible.

I would recommend just using `createrepo` instead.
